FROM wizbii/php:8.1

COPY --from=php:8.1-cli-alpine /usr/local/bin/phpdbg /usr/local/bin/

RUN apk add --update linux-headers && \
    install-php-extensions xdebug && \
    echo "xdebug.mode=coverage" >>  /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

